# Generated by Django 4.0.5 on 2022-08-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_is_admin_account_is_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
