# Generated by Django 4.0.5 on 2022-08-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_delete_tag_alter_post_slug_alter_post_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
